
//----------------------------------------------------
// The following code was generated by CUP v0.10k TUM Edition 20050516
// Mon Dec 02 13:58:33 CET 2019
//----------------------------------------------------

package org.conqat.lib.simulink.targetlink;

import java.util.List;
import java.util.ArrayList;
import org.conqat.lib.simulink.builder.MDLParserException;
import org.conqat.lib.commons.collections.ImmutablePair;
import java.util.ArrayList;
import org.conqat.lib.commons.string.StringUtils;

/** CUP v0.10k TUM Edition 20050516 generated parser.
  * @version Mon Dec 02 13:58:33 CET 2019
  */
public class TargetlinkDataParser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public TargetlinkDataParser() {super();}

  /** Constructor which sets the default scanner. */
  public TargetlinkDataParser(java_cup.runtime.Scanner s) {super(s);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\062\000\002\002\004\000\002\003\003\000\002\003" +
    "\003\000\002\003\004\000\002\004\006\000\002\005\005" +
    "\000\002\006\005\000\002\006\003\000\002\007\005\000" +
    "\002\007\003\000\002\010\005\000\002\011\005\000\002" +
    "\027\003\000\002\027\003\000\002\027\003\000\002\027" +
    "\003\000\002\030\003\000\002\030\003\000\002\030\003" +
    "\000\002\030\003\000\002\013\003\000\002\013\003\000" +
    "\002\013\003\000\002\013\003\000\002\012\003\000\002" +
    "\012\003\000\002\012\003\000\002\014\006\000\002\014" +
    "\010\000\002\014\005\000\002\016\005\000\002\016\003" +
    "\000\002\020\004\000\002\020\003\000\002\015\005\000" +
    "\002\017\005\000\002\021\005\000\002\021\004\000\002" +
    "\022\005\000\002\022\004\000\002\023\005\000\002\023" +
    "\003\000\002\024\003\000\002\024\005\000\002\025\003" +
    "\000\002\025\003\000\002\025\003\000\002\025\003\000" +
    "\002\026\003\000\002\026\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\124\000\010\004\010\006\005\021\011\001\002\000" +
    "\004\002\uffff\001\002\000\004\014\111\001\002\000\004" +
    "\002\107\001\002\000\004\002\000\001\002\000\004\005" +
    "\106\001\002\000\004\012\012\001\002\000\004\014\014" +
    "\001\002\000\006\013\104\020\103\001\002\000\004\020" +
    "\016\001\002\000\006\013\ufffa\020\ufffa\001\002\000\022" +
    "\004\034\006\017\010\035\014\026\015\025\016\032\017" +
    "\033\021\011\001\002\000\014\006\017\014\026\015\025" +
    "\016\032\017\033\001\002\000\024\005\uffe9\006\uffe9\007" +
    "\uffe9\013\uffe9\014\uffe9\015\uffe9\016\uffe9\017\uffe9\020\uffe9" +
    "\001\002\000\006\013\ufff5\020\ufff5\001\002\000\024\005" +
    "\uffe8\006\uffe8\007\uffe8\013\uffe8\014\uffe8\015\uffe8\016\uffe8" +
    "\017\uffe8\020\uffe8\001\002\000\006\013\ufff3\020\ufff3\001" +
    "\002\000\012\023\066\024\067\025\064\026\070\001\002" +
    "\000\034\005\uffed\006\uffed\007\uffed\013\uffed\014\uffed\015" +
    "\uffed\016\uffed\017\uffed\020\uffed\023\uffd1\024\uffd1\025\uffd1" +
    "\026\uffd1\001\002\000\024\005\uffeb\006\uffeb\007\uffeb\013" +
    "\uffeb\014\uffeb\015\uffeb\016\uffeb\017\uffeb\020\uffeb\001\002" +
    "\000\024\005\uffe7\006\uffe7\007\uffe7\013\uffe7\014\uffe7\015" +
    "\uffe7\016\uffe7\017\uffe7\020\uffe7\001\002\000\006\013\ufff7" +
    "\020\ufff7\001\002\000\006\013\ufff4\020\ufff4\001\002\000" +
    "\034\005\uffec\006\uffec\007\uffec\013\uffec\014\uffec\015\uffec" +
    "\016\uffec\017\uffec\020\uffec\023\uffd0\024\uffd0\025\uffd0\026" +
    "\uffd0\001\002\000\026\005\uffea\006\uffea\007\uffea\012\056" +
    "\013\uffea\014\uffea\015\uffea\016\uffea\017\uffea\020\uffea\001" +
    "\002\000\016\005\053\006\017\014\026\015\025\016\032" +
    "\017\033\001\002\000\010\004\040\011\037\014\043\001" +
    "\002\000\006\013\ufff2\020\ufff2\001\002\000\010\007\uffda" +
    "\013\uffda\020\uffda\001\002\000\004\014\047\001\002\000" +
    "\006\011\044\022\045\001\002\000\006\011\uffd8\022\uffd8" +
    "\001\002\000\006\011\uffd7\022\uffd7\001\002\000\010\007" +
    "\uffdb\013\uffdb\020\uffdb\001\002\000\006\004\040\014\043" +
    "\001\002\000\006\011\uffd9\022\uffd9\001\002\000\004\005" +
    "\050\001\002\000\006\011\uffd6\022\uffd6\001\002\000\016" +
    "\005\uffe0\006\uffe0\014\uffe0\015\uffe0\016\uffe0\017\uffe0\001" +
    "\002\000\016\005\055\006\017\014\026\015\025\016\032" +
    "\017\033\001\002\000\010\007\uffdc\013\uffdc\020\uffdc\001" +
    "\002\000\016\005\uffe1\006\uffe1\014\uffe1\015\uffe1\016\uffe1" +
    "\017\uffe1\001\002\000\010\007\uffdd\013\uffdd\020\uffdd\001" +
    "\002\000\014\006\017\014\026\015\025\016\032\017\033" +
    "\001\002\000\010\007\uffe2\013\uffe2\020\uffe2\001\002\000" +
    "\006\013\062\020\061\001\002\000\014\006\017\014\026" +
    "\015\025\016\032\017\033\001\002\000\024\005\uffe6\006" +
    "\uffe6\007\uffe6\013\uffe6\014\uffe6\015\uffe6\016\uffe6\017\uffe6" +
    "\020\uffe6\001\002\000\010\007\uffe3\013\uffe3\020\uffe3\001" +
    "\002\000\004\017\uffd3\001\002\000\004\017\071\001\002" +
    "\000\004\017\uffd5\001\002\000\004\017\uffd4\001\002\000" +
    "\004\017\uffd2\001\002\000\004\012\072\001\002\000\014" +
    "\006\017\014\026\015\025\016\032\017\033\001\002\000" +
    "\006\013\074\020\061\001\002\000\024\005\uffe5\006\uffe5" +
    "\007\uffe5\013\uffe5\014\uffe5\015\uffe5\016\uffe5\017\uffe5\020" +
    "\uffe5\001\002\000\006\007\101\020\100\001\002\000\006" +
    "\007\077\020\061\001\002\000\024\005\uffe4\006\uffe4\007" +
    "\uffe4\013\uffe4\014\uffe4\015\uffe4\016\uffe4\017\uffe4\020\uffe4" +
    "\001\002\000\004\017\102\001\002\000\024\005\uffdf\006" +
    "\uffdf\007\uffdf\013\uffdf\014\uffdf\015\uffdf\016\uffdf\017\uffdf" +
    "\020\uffdf\001\002\000\006\007\uffde\020\uffde\001\002\000" +
    "\004\014\014\001\002\000\010\002\ufffd\013\ufffd\020\ufffd" +
    "\001\002\000\006\013\ufffb\020\ufffb\001\002\000\004\002" +
    "\ufffe\001\002\000\004\002\001\001\002\000\006\007\125" +
    "\020\124\001\002\000\004\020\113\001\002\000\006\007" +
    "\ufff8\020\ufff8\001\002\000\020\004\034\006\005\010\035" +
    "\014\026\015\116\016\121\017\122\001\002\000\006\007" +
    "\ufff1\020\ufff1\001\002\000\006\007\uffef\020\uffef\001\002" +
    "\000\006\007\uffed\020\uffed\001\002\000\006\007\ufff6\020" +
    "\ufff6\001\002\000\006\007\ufff0\020\ufff0\001\002\000\006" +
    "\007\uffec\020\uffec\001\002\000\006\007\uffea\020\uffea\001" +
    "\002\000\006\007\uffee\020\uffee\001\002\000\004\014\111" +
    "\001\002\000\010\002\ufffc\007\ufffc\020\ufffc\001\002\000" +
    "\006\007\ufff9\020\ufff9\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\124\000\010\003\005\004\006\005\003\001\001\000" +
    "\002\001\001\000\006\007\107\011\111\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\006\012\010\014\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\024\004\030\012" +
    "\020\013\017\014\021\015\026\021\022\022\035\026\023" +
    "\027\027\001\001\000\020\012\056\013\017\014\021\015" +
    "\026\016\075\017\074\026\023\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\025\064\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\016\012\050\013\017" +
    "\014\021\015\026\020\051\026\023\001\001\000\006\023" +
    "\040\024\041\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\024\045\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\014\012\053\013\017\014\021\015\026" +
    "\026\023\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\016\012\056\013\017\014\021\015\026" +
    "\016\057\026\023\001\001\000\002\001\001\000\002\001" +
    "\001\000\014\012\062\013\017\014\021\015\026\026\023" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\016\012\056\013" +
    "\017\014\021\015\026\016\072\026\023\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\010\104\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\014\005\117\013\113\021\114\022\122\030\116\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\011\125\001\001\000" +
    "\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$TargetlinkDataParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$TargetlinkDataParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$TargetlinkDataParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


 
  public static void debug(String message) {
    System.out.println(message);
  }
  
  public void report_error(String message, Object info) {
    System.err.println(message);
  }
 
  /* Change the method report_fatal_error so when it reports a fatal
     error it will display the line and column number of where the
     fatal error occurred in the input as well as the reason for the
     fatal error which is passed into the method in the object
     'message' and then exit.*/
  public void report_fatal_error(String message, Object info) throws Exception {     
      if (info instanceof java_cup.runtime.Symbol) {
        java_cup.runtime.Symbol symbol = ((java_cup.runtime.Symbol) info);
        
        int line = symbol.left+1;
        int column = symbol.right+1;
        
        throw new MDLParserException(message+" at line: "+line+", column: "+column, line, column);
        
      } else {
        throw new MDLParserException(message);
      }
  }
  
  public static TargetlinkStruct buildStruct (List<ImmutablePair> l) {
      TargetlinkStruct struct = new TargetlinkStruct();
	  for (ImmutablePair<String, Object> pair : l) {
			Object value = pair.getSecond();
			if (value instanceof TargetlinkStruct) {
			  struct.addChild(pair.getFirst(), (TargetlinkStruct)value);
			} else if (value instanceof String) {
			  struct.setParameter(pair.getFirst(), (String)value);
			} else {
			  throw new IllegalStateException("Unknown value type.");
			}
	  }
	  return struct;
  }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$TargetlinkDataParser$actions {
  private final TargetlinkDataParser parser;

  /** Constructor */
  CUP$TargetlinkDataParser$actions(TargetlinkDataParser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$TargetlinkDataParser$do_action(
    int                        CUP$TargetlinkDataParser$act_num,
    java_cup.runtime.lr_parser CUP$TargetlinkDataParser$parser,
    java.util.Stack            CUP$TargetlinkDataParser$stack,
    int                        CUP$TargetlinkDataParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$TargetlinkDataParser$result;

      /* select the action based on the action number */
      switch (CUP$TargetlinkDataParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // NumberLiteral ::= FLOAT_LITERAL 
            {
              String RESULT = null;
		int lleft = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right;
		Object l = (Object)((java_cup.runtime.Symbol) CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).value;
		 RESULT=l.toString(); 
              CUP$TargetlinkDataParser$result = new java_cup.runtime.Symbol(20/*NumberLiteral*/, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right, RESULT);
            }
          return CUP$TargetlinkDataParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // NumberLiteral ::= INT_LITERAL 
            {
              String RESULT = null;
		int lleft = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right;
		Object l = (Object)((java_cup.runtime.Symbol) CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).value;
		 RESULT=l.toString(); 
              CUP$TargetlinkDataParser$result = new java_cup.runtime.Symbol(20/*NumberLiteral*/, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right, RESULT);
            }
          return CUP$TargetlinkDataParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // Operator ::= DIV 
            {
              String RESULT = null;
		 RESULT="/"; 
              CUP$TargetlinkDataParser$result = new java_cup.runtime.Symbol(19/*Operator*/, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right, RESULT);
            }
          return CUP$TargetlinkDataParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // Operator ::= MULT 
            {
              String RESULT = null;
		 RESULT="*"; 
              CUP$TargetlinkDataParser$result = new java_cup.runtime.Symbol(19/*Operator*/, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right, RESULT);
            }
          return CUP$TargetlinkDataParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // Operator ::= MINUS 
            {
              String RESULT = null;
		 RESULT="-"; 
              CUP$TargetlinkDataParser$result = new java_cup.runtime.Symbol(19/*Operator*/, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right, RESULT);
            }
          return CUP$TargetlinkDataParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // Operator ::= PLUS 
            {
              String RESULT = null;
		 RESULT="+"; 
              CUP$TargetlinkDataParser$result = new java_cup.runtime.Symbol(19/*Operator*/, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right, RESULT);
            }
          return CUP$TargetlinkDataParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // ListItem ::= LBRACK STRING_LITERAL RBRACK 
            {
              String RESULT = null;
		int lleft = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-1)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-1)).right;
		Object l = (Object)((java_cup.runtime.Symbol) CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-1)).value;
		 RESULT = "["+l.toString()+"]"; 
              CUP$TargetlinkDataParser$result = new java_cup.runtime.Symbol(18/*ListItem*/, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right, RESULT);
            }
          return CUP$TargetlinkDataParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // ListItem ::= STRING_LITERAL 
            {
              String RESULT = null;
		int lleft = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right;
		Object l = (Object)((java_cup.runtime.Symbol) CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).value;
		 RESULT = l.toString(); 
              CUP$TargetlinkDataParser$result = new java_cup.runtime.Symbol(18/*ListItem*/, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right, RESULT);
            }
          return CUP$TargetlinkDataParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // ListItems ::= ListItem 
            {
              List<String> RESULT = null;
		int ileft = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).value;
		 ArrayList<String> l = new ArrayList<String>();
                 l.add(i);
                 RESULT = l;
               
              CUP$TargetlinkDataParser$result = new java_cup.runtime.Symbol(17/*ListItems*/, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right, RESULT);
            }
          return CUP$TargetlinkDataParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // ListItems ::= ListItems SEMICOLON ListItem 
            {
              List<String> RESULT = null;
		int lleft = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-2)).right;
		List<String> l = (List<String>)((java_cup.runtime.Symbol) CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-2)).value;
		int ileft = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).value;
		 l.add(i);
                 RESULT = l; 
              CUP$TargetlinkDataParser$result = new java_cup.runtime.Symbol(17/*ListItems*/, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right, RESULT);
            }
          return CUP$TargetlinkDataParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // List ::= DLBRACE DRBRACE 
            {
              String RESULT = null;
		  RESULT = "{{}}"; 
              CUP$TargetlinkDataParser$result = new java_cup.runtime.Symbol(16/*List*/, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right, RESULT);
            }
          return CUP$TargetlinkDataParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // List ::= DLBRACE ListItems DRBRACE 
            {
              String RESULT = null;
		int lleft = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-1)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-1)).right;
		List<String> l = (List<String>)((java_cup.runtime.Symbol) CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-1)).value;
		  RESULT = "{{"+StringUtils.concat(l, ";") +"}}"; 
              CUP$TargetlinkDataParser$result = new java_cup.runtime.Symbol(16/*List*/, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right, RESULT);
            }
          return CUP$TargetlinkDataParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // Array ::= LBRACK RBRACK 
            {
              String RESULT = null;
		 RESULT = "[]"; 
              CUP$TargetlinkDataParser$result = new java_cup.runtime.Symbol(15/*Array*/, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right, RESULT);
            }
          return CUP$TargetlinkDataParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // Array ::= LBRACK LiteralList RBRACK 
            {
              String RESULT = null;
		int lleft = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-1)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-1)).right;
		List<String> l = (List<String>)((java_cup.runtime.Symbol) CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-1)).value;
		  RESULT = StringUtils.concat(l, " "); 
              CUP$TargetlinkDataParser$result = new java_cup.runtime.Symbol(15/*Array*/, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right, RESULT);
            }
          return CUP$TargetlinkDataParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // Identifiers ::= Identifiers COMMA IDENTIFIER 
            {
              String RESULT = null;
		int i1left = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-2)).left;
		int i1right = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-2)).right;
		String i1 = (String)((java_cup.runtime.Symbol) CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-2)).value;
		int i2left = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).left;
		int i2right = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right;
		Object i2 = (Object)((java_cup.runtime.Symbol) CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).value;
		 RESULT = i1.toString() +","+i2.toString(); 
              CUP$TargetlinkDataParser$result = new java_cup.runtime.Symbol(13/*Identifiers*/, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right, RESULT);
            }
          return CUP$TargetlinkDataParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // CompoundIdentifier ::= LBRACE Identifiers RBRACE 
            {
              String RESULT = null;
		int ileft = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-1)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-1)).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-1)).value;
		 RESULT = "{"+i.toString()+"}"; 
              CUP$TargetlinkDataParser$result = new java_cup.runtime.Symbol(11/*CompoundIdentifier*/, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right, RESULT);
            }
          return CUP$TargetlinkDataParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // LiteralList ::= Literal 
            {
              List<String> RESULT = null;
		int lleft = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right;
		String l = (String)((java_cup.runtime.Symbol) CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).value;
		 ArrayList<String> list = new ArrayList<String>();
             list.add(l);
             RESULT = list; 
              CUP$TargetlinkDataParser$result = new java_cup.runtime.Symbol(14/*LiteralList*/, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right, RESULT);
            }
          return CUP$TargetlinkDataParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // LiteralList ::= LiteralList Literal 
            {
              List<String> RESULT = null;
		int listleft = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-1)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-1)).right;
		List<String> list = (List<String>)((java_cup.runtime.Symbol) CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-1)).value;
		int lleft = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right;
		String l = (String)((java_cup.runtime.Symbol) CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).value;
		 list.add(l);
                RESULT = list; 
              CUP$TargetlinkDataParser$result = new java_cup.runtime.Symbol(14/*LiteralList*/, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right, RESULT);
            }
          return CUP$TargetlinkDataParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // Literals ::= Literal 
            {
              String RESULT = null;
		int lleft = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right;
		String l = (String)((java_cup.runtime.Symbol) CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).value;
		 RESULT = l.toString(); 
              CUP$TargetlinkDataParser$result = new java_cup.runtime.Symbol(12/*Literals*/, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right, RESULT);
            }
          return CUP$TargetlinkDataParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // Literals ::= Literals COMMA Literal 
            {
              String RESULT = null;
		int lleft = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-2)).right;
		String l = (String)((java_cup.runtime.Symbol) CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-2)).value;
		int ileft = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).value;
		 RESULT = l.toString() +","+i.toString(); 
              CUP$TargetlinkDataParser$result = new java_cup.runtime.Symbol(12/*Literals*/, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right, RESULT);
            }
          return CUP$TargetlinkDataParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // CompoundLiteral ::= LBRACE Literals RBRACE 
            {
              String RESULT = null;
		int lleft = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-1)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-1)).right;
		String l = (String)((java_cup.runtime.Symbol) CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-1)).value;
		 RESULT = "{"+l.toString()+"}"; 
              CUP$TargetlinkDataParser$result = new java_cup.runtime.Symbol(10/*CompoundLiteral*/, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right, RESULT);
            }
          return CUP$TargetlinkDataParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // CompoundLiteral ::= NumberLiteral Operator IDENTIFIER LPAREN Literals RPAREN 
            {
              String RESULT = null;
		int nleft = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-5)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-5)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-5)).value;
		int oleft = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-4)).left;
		int oright = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-4)).right;
		String o = (String)((java_cup.runtime.Symbol) CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-4)).value;
		int ileft = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-3)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-3)).right;
		Object i = (Object)((java_cup.runtime.Symbol) CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-3)).value;
		int lleft = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-1)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-1)).right;
		String l = (String)((java_cup.runtime.Symbol) CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-1)).value;
		 RESULT = n+o+i.toString()+"("+l.toString()+")"; 
              CUP$TargetlinkDataParser$result = new java_cup.runtime.Symbol(10/*CompoundLiteral*/, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-5)).left, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right, RESULT);
            }
          return CUP$TargetlinkDataParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // CompoundLiteral ::= IDENTIFIER LPAREN Literals RPAREN 
            {
              String RESULT = null;
		int ileft = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-3)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-3)).right;
		Object i = (Object)((java_cup.runtime.Symbol) CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-3)).value;
		int lleft = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-1)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-1)).right;
		String l = (String)((java_cup.runtime.Symbol) CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-1)).value;
		 RESULT = i.toString()+"("+l.toString()+")"; 
              CUP$TargetlinkDataParser$result = new java_cup.runtime.Symbol(10/*CompoundLiteral*/, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-3)).left, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right, RESULT);
            }
          return CUP$TargetlinkDataParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // Literal ::= CompoundIdentifier 
            {
              String RESULT = null;
		int ileft = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).value;
		 RESULT = i.toString(); 
              CUP$TargetlinkDataParser$result = new java_cup.runtime.Symbol(8/*Literal*/, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right, RESULT);
            }
          return CUP$TargetlinkDataParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // Literal ::= CompoundLiteral 
            {
              String RESULT = null;
		int ileft = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).value;
		 RESULT = i.toString(); 
              CUP$TargetlinkDataParser$result = new java_cup.runtime.Symbol(8/*Literal*/, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right, RESULT);
            }
          return CUP$TargetlinkDataParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // Literal ::= NewStyleLiteral 
            {
              String RESULT = null;
		int lleft = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right;
		String l = (String)((java_cup.runtime.Symbol) CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).value;
		 RESULT = l; 
              CUP$TargetlinkDataParser$result = new java_cup.runtime.Symbol(8/*Literal*/, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right, RESULT);
            }
          return CUP$TargetlinkDataParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // NewStyleLiteral ::= IDENTIFIER 
            {
              String RESULT = null;
		int ileft = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right;
		Object i = (Object)((java_cup.runtime.Symbol) CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).value;
		 RESULT = i.toString(); 
              CUP$TargetlinkDataParser$result = new java_cup.runtime.Symbol(9/*NewStyleLiteral*/, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right, RESULT);
            }
          return CUP$TargetlinkDataParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // NewStyleLiteral ::= STRING_LITERAL 
            {
              String RESULT = null;
		int lleft = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right;
		Object l = (Object)((java_cup.runtime.Symbol) CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).value;
		 RESULT = l.toString(); 
              CUP$TargetlinkDataParser$result = new java_cup.runtime.Symbol(9/*NewStyleLiteral*/, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right, RESULT);
            }
          return CUP$TargetlinkDataParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // NewStyleLiteral ::= FLOAT_LITERAL 
            {
              String RESULT = null;
		int lleft = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right;
		Object l = (Object)((java_cup.runtime.Symbol) CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).value;
		 RESULT = l.toString(); 
              CUP$TargetlinkDataParser$result = new java_cup.runtime.Symbol(9/*NewStyleLiteral*/, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right, RESULT);
            }
          return CUP$TargetlinkDataParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // NewStyleLiteral ::= INT_LITERAL 
            {
              String RESULT = null;
		int lleft = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right;
		Object l = (Object)((java_cup.runtime.Symbol) CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).value;
		 RESULT = l.toString(); 
              CUP$TargetlinkDataParser$result = new java_cup.runtime.Symbol(9/*NewStyleLiteral*/, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right, RESULT);
            }
          return CUP$TargetlinkDataParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // NewStyleValue ::= List 
            {
              Object RESULT = null;
		int lleft = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right;
		String l = (String)((java_cup.runtime.Symbol) CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).value;
		 RESULT = l; 
              CUP$TargetlinkDataParser$result = new java_cup.runtime.Symbol(22/*NewStyleValue*/, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right, RESULT);
            }
          return CUP$TargetlinkDataParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // NewStyleValue ::= Array 
            {
              Object RESULT = null;
		int aleft = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).value;
		 RESULT = a; 
              CUP$TargetlinkDataParser$result = new java_cup.runtime.Symbol(22/*NewStyleValue*/, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right, RESULT);
            }
          return CUP$TargetlinkDataParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // NewStyleValue ::= NewStyleStruct 
            {
              Object RESULT = null;
		int sleft = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right;
		TargetlinkStruct s = (TargetlinkStruct)((java_cup.runtime.Symbol) CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).value;
		 RESULT = s; 
              CUP$TargetlinkDataParser$result = new java_cup.runtime.Symbol(22/*NewStyleValue*/, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right, RESULT);
            }
          return CUP$TargetlinkDataParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // NewStyleValue ::= NewStyleLiteral 
            {
              Object RESULT = null;
		int lleft = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right;
		String l = (String)((java_cup.runtime.Symbol) CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).value;
		 RESULT = l; 
              CUP$TargetlinkDataParser$result = new java_cup.runtime.Symbol(22/*NewStyleValue*/, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right, RESULT);
            }
          return CUP$TargetlinkDataParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // Value ::= List 
            {
              Object RESULT = null;
		int lleft = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right;
		String l = (String)((java_cup.runtime.Symbol) CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).value;
		 RESULT = l; 
              CUP$TargetlinkDataParser$result = new java_cup.runtime.Symbol(21/*Value*/, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right, RESULT);
            }
          return CUP$TargetlinkDataParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // Value ::= Array 
            {
              Object RESULT = null;
		int aleft = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).value;
		 RESULT = a; 
              CUP$TargetlinkDataParser$result = new java_cup.runtime.Symbol(21/*Value*/, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right, RESULT);
            }
          return CUP$TargetlinkDataParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // Value ::= OldStyleStruct 
            {
              Object RESULT = null;
		int sleft = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right;
		TargetlinkStruct s = (TargetlinkStruct)((java_cup.runtime.Symbol) CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).value;
		 RESULT = s; 
              CUP$TargetlinkDataParser$result = new java_cup.runtime.Symbol(21/*Value*/, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right, RESULT);
            }
          return CUP$TargetlinkDataParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // Value ::= Literal 
            {
              Object RESULT = null;
		int lleft = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right;
		String l = (String)((java_cup.runtime.Symbol) CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).value;
		 RESULT = l; 
              CUP$TargetlinkDataParser$result = new java_cup.runtime.Symbol(21/*Value*/, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right, RESULT);
            }
          return CUP$TargetlinkDataParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // NewStyleKeyValue ::= STRING_LITERAL COMMA NewStyleValue 
            {
              ImmutablePair RESULT = null;
		int lleft = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-2)).right;
		Object l = (Object)((java_cup.runtime.Symbol) CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-2)).value;
		int vleft = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).value;
		 RESULT = new ImmutablePair<String, Object>(l.toString(), v); 
              CUP$TargetlinkDataParser$result = new java_cup.runtime.Symbol(7/*NewStyleKeyValue*/, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right, RESULT);
            }
          return CUP$TargetlinkDataParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // KeyValue ::= STRING_LITERAL COMMA Value 
            {
              ImmutablePair RESULT = null;
		int lleft = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-2)).right;
		Object l = (Object)((java_cup.runtime.Symbol) CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-2)).value;
		int vleft = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).value;
		 RESULT = new ImmutablePair<String, Object>(l.toString(), v); 
              CUP$TargetlinkDataParser$result = new java_cup.runtime.Symbol(6/*KeyValue*/, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right, RESULT);
            }
          return CUP$TargetlinkDataParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // NewStyleKeyValueList ::= NewStyleKeyValue 
            {
              List<ImmutablePair> RESULT = null;
		int kleft = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).left;
		int kright = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right;
		ImmutablePair k = (ImmutablePair)((java_cup.runtime.Symbol) CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).value;
		 ArrayList<ImmutablePair> list = new ArrayList<ImmutablePair>();
		                     list.add(k);
		                     RESULT = list; 
              CUP$TargetlinkDataParser$result = new java_cup.runtime.Symbol(5/*NewStyleKeyValueList*/, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right, RESULT);
            }
          return CUP$TargetlinkDataParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // NewStyleKeyValueList ::= NewStyleKeyValueList COMMA NewStyleKeyValue 
            {
              List<ImmutablePair> RESULT = null;
		int lleft = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-2)).right;
		List<ImmutablePair> l = (List<ImmutablePair>)((java_cup.runtime.Symbol) CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-2)).value;
		int kleft = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).left;
		int kright = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right;
		ImmutablePair k = (ImmutablePair)((java_cup.runtime.Symbol) CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).value;
		 l.add(k);
		                     RESULT = l; 
              CUP$TargetlinkDataParser$result = new java_cup.runtime.Symbol(5/*NewStyleKeyValueList*/, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right, RESULT);
            }
          return CUP$TargetlinkDataParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // KeyValueList ::= KeyValue 
            {
              List<ImmutablePair> RESULT = null;
		int kleft = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).left;
		int kright = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right;
		ImmutablePair k = (ImmutablePair)((java_cup.runtime.Symbol) CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).value;
		 ArrayList<ImmutablePair> list = new ArrayList<ImmutablePair>();
                     list.add(k);
                     RESULT = list; 
              CUP$TargetlinkDataParser$result = new java_cup.runtime.Symbol(4/*KeyValueList*/, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right, RESULT);
            }
          return CUP$TargetlinkDataParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // KeyValueList ::= KeyValueList COMMA KeyValue 
            {
              List<ImmutablePair> RESULT = null;
		int lleft = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-2)).right;
		List<ImmutablePair> l = (List<ImmutablePair>)((java_cup.runtime.Symbol) CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-2)).value;
		int kleft = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).left;
		int kright = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right;
		ImmutablePair k = (ImmutablePair)((java_cup.runtime.Symbol) CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).value;
		 l.add(k);
                     RESULT = l; 
              CUP$TargetlinkDataParser$result = new java_cup.runtime.Symbol(4/*KeyValueList*/, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right, RESULT);
            }
          return CUP$TargetlinkDataParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // NewStyleStruct ::= LBRACE NewStyleKeyValueList RBRACE 
            {
              TargetlinkStruct RESULT = null;
		int lleft = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-1)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-1)).right;
		List<ImmutablePair> l = (List<ImmutablePair>)((java_cup.runtime.Symbol) CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-1)).value;
		 RESULT = TargetlinkDataParser.buildStruct (l); 
              CUP$TargetlinkDataParser$result = new java_cup.runtime.Symbol(3/*NewStyleStruct*/, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right, RESULT);
            }
          return CUP$TargetlinkDataParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // OldStyleStruct ::= STRUCT LPAREN KeyValueList RPAREN 
            {
              TargetlinkStruct RESULT = null;
		int lleft = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-1)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-1)).right;
		List<ImmutablePair> l = (List<ImmutablePair>)((java_cup.runtime.Symbol) CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-1)).value;
		 RESULT = TargetlinkDataParser.buildStruct (l); 
              CUP$TargetlinkDataParser$result = new java_cup.runtime.Symbol(2/*OldStyleStruct*/, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-3)).left, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right, RESULT);
            }
          return CUP$TargetlinkDataParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // TargetLinkData ::= LBRACK RBRACK 
            {
              TargetlinkStruct RESULT = null;
		 RESULT = new TargetlinkStruct(); 
              CUP$TargetlinkDataParser$result = new java_cup.runtime.Symbol(1/*TargetLinkData*/, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right, RESULT);
            }
          return CUP$TargetlinkDataParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // TargetLinkData ::= NewStyleStruct 
            {
              TargetlinkStruct RESULT = null;
		int sleft = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right;
		TargetlinkStruct s = (TargetlinkStruct)((java_cup.runtime.Symbol) CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).value;
		 RESULT = s; 
              CUP$TargetlinkDataParser$result = new java_cup.runtime.Symbol(1/*TargetLinkData*/, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right, RESULT);
            }
          return CUP$TargetlinkDataParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // TargetLinkData ::= OldStyleStruct 
            {
              TargetlinkStruct RESULT = null;
		int sleft = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right;
		TargetlinkStruct s = (TargetlinkStruct)((java_cup.runtime.Symbol) CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).value;
		 RESULT = s; 
              CUP$TargetlinkDataParser$result = new java_cup.runtime.Symbol(1/*TargetLinkData*/, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right, RESULT);
            }
          return CUP$TargetlinkDataParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= TargetLinkData EOF 
            {
              Object RESULT = null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-1)).right;
		TargetlinkStruct start_val = (TargetlinkStruct)((java_cup.runtime.Symbol) CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-1)).value;
		RESULT = start_val;
              CUP$TargetlinkDataParser$result = new java_cup.runtime.Symbol(0/*$START*/, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$TargetlinkDataParser$stack.elementAt(CUP$TargetlinkDataParser$top-0)).right, RESULT);
            }
          /* ACCEPT */
          CUP$TargetlinkDataParser$parser.done_parsing();
          return CUP$TargetlinkDataParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

